### ISSUE TITLE
Only listing a single state for selected country

### ISSUE THREAD

**Issue by stephenmorton** [wisdom-diala/countrypkg-laravel#1]
Hi Wisdom, thanks for the package, this will help me a lot.
I have a problem, that I cannot figure out. All the code looks fine and I copied from your youtube video.
I have gone through the database tables and can see all the Country data and State data as I would expect. My country is Australia, country_id 13
I can see several states in the states database  for this country, (NSW, VIC ... Western Australia)
I have created the view, route and controller. I have imported the models into my controller.
When I change the Country in my view, the state dropdown populates, but it only populates with the last value in the states table for that country. Ie, in my case, when I select Australia (country_id 13), it just lists Western Australia as a state in the state dropdown.

Here is my controller

    public function getStates()
    {
        $country_id = request('country');
        $states = State::where('country_id', $country_id)->get();
        $option = "<option value=''>Select State</option>";
        foreach ($states as $state) {
            $option = '<option value="'.$state->name.'">'.$state->name.'</option>';
        }
        return $option;
    }

Here is my View (country and state dropdowns) - ps, I have included the jquery cdn

                        <div class="form-group col-sm-11 col-md-7">
                            <label class="form-country" for="country">Country</label>
                            <select v-model="form.country" type="text" class="form-control" id="country" name="country">
                                <option value="">Please Select</option>
                                @foreach ($countries as $country)
                                    <option value="{{ $country->id }}">{{ $country->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group col-sm-11 col-md-7">
                            <label class="form-state" for="state">State</label>
                            <select v-model="form.state" class="form-control" id="state" name="state">
                                
                            </select>
                        </div>

Here is my jquery script in the view

  <script>
    $(document).ready(function(){
        $("#country").change(function(){
            let country_id = this.value;
            $.get('/get_states?country='+country_id, function(data){
                $("#state").html(data);
            })
        })
    })
</script>

Sorry to bug you about this, as I don't think it is an issue with your package, it is obviously just a jquery issue, not sure if it has changes since you made your youtube video or something. I followed your testing in the video, and can see console log of the correct country_id when I change country dropdown.
Any help would be greatly appreciated.

**Comment by wisdom-diala** [comment]
Hello Stephen,
Sorry for the late reply, I have been busy with work
Kindly use the code below in your controller as you forgot to concatenate(.=) the option value.
```php
public function getStates()
{
    $country_id = request('country');
    $states = State::where('country_id', $country_id)->get();
    $option = "<option value=''>Select State</option>";
    foreach ($states as $state) {
        $option .= '<option value="'.$state->name.'">'.$state->name.'</option>';
    }
    return $option;
}
```

**Comment by stephenmorton** [comment]
Thankyou wisdom, I will give that a try.

Stephen Morton
Manager
Total Telco Group Pty Ltd

***@***.***
02 8488 3150<tel:02%208488%203150> | 0418 111 068<tel:0418%20111%20068>
***@***.***
www.totaltelco.com.au<https://www.totaltelco.com.au/>
