### ISSUE TITLE
Merged Pull Request #2 from Aug 2023 still not released to production package

### ISSUE THREAD

**Issue by Kenneth-Inkum** [wisdom-diala/countrypkg-laravel#3]
I made a pull request in August 2023 where I added some new regions in Ghana and you successfully merged the request. However, I'm using the package in a new project and I noticed it's still the old data rather than the updated list. Kindly help with this.

**Comment by wisdom-diala** [comment]
> I made a pull request in August 2023 where I added some new regions in Ghana and you successfully merged the request. However, I'm using the package in a new project and I noticed it's still the old data rather than the updated list. Kindly help with this.

The PR was merged as you stated, can you please try running composer update.
